# nifty_index.py

NIFTY_50 = [
    "ADANIPORTS", "APOLLOHOSP", "ASIANPAINT", "AXISBANK", "BAJAJ-AUTO",
    "BAJFINANCE", "BAJAJFINSV", "BHARTIARTL", "BPCL", "BRITANNIA",
    "CIPLA", "COALINDIA", "DIVISLAB", "DRREDDY", "EICHERMOT",
    "GRASIM", "HCLTECH", "HDFC", "HDFCBANK", "HEROMOTOCO",
    "HINDALCO", "HINDUNILVR", "ICICIBANK", "INDUSINDBK", "INFY",
    "ITC", "JSWSTEEL", "KOTAKBANK", "LT", "M&M",
    "MARUTI", "NESTLEIND", "NTPC", "ONGC", "POWERGRID",
    "RELIANCE", "SBILIFE", "SBIN", "SHREECEM", "SUNPHARMA",
    "TATACONSUM", "TATAMOTORS", "TATASTEEL", "TCS", "TECHM",
    "TITAN", "ULTRACEMCO", "UPL", "WIPRO"
]

NIFTY_BANK = [
    "AXISBANK", "BANDHANBNK", "BANKBARODA", "FEDERALBNK", "HDFCBANK",
    "ICICIBANK", "IDFCFIRSTB", "INDUSINDBK", "KOTAKBANK", "PNB",
    "SBIN", "AUBANK"
]

NIFTY_OIL_GAS = [
    "ADANIGREEN", "ADANITRANS", "BPCL", "CASTROLIND", "GAIL",
    "GUJGASLTD", "HINDPETRO", "IGL", "INDRAPRASTH", "IOC",
    "MGL", "ONGC", "OIL", "PETRONET", "RELIANCE"
]

NIFTY_IT = [
    "COFORGE", "HCLTECH", "INFY", "LTIM", "MPHASIS",
    "PERSISTENT", "TCS", "TECHM", "WIPRO"
]

NIFTY_FMCG = [
    "BRITANNIA", "COLPAL", "DABUR", "EMAMILTD", "GODREJCP",
    "HINDUNILVR", "ITC", "MARICO", "NESTLEIND", "TATACONSUM",
    "UBL", "UNITDSPR", "VARUN", "VBL"
]

NIFTY_PHARMA = [
    "ALKEM", "AUROBINDO", "BIOCON", "CADILAHC", "CIPLA",
    "DIVISLAB", "DRREDDY", "GLAND", "GLENMARK", "IPCALAB",
    "LAURUSLABS", "LUPIN", "NATCOPHARM", "PFIZER", "SANOFI",
    "SUNPHARMA", "TORNTPHARM", "ZYDUSLIFE"
]

NIFTY_AUTO = [
    "ASHOKLEY", "BAJAJ-AUTO", "BALKRISIND", "BOSCHLTD", "EICHERMOT",
    "HEROMOTOCO", "MAHINDCIE", "M&M", "MARUTI", "MOTHERSON",
    "SAMRATFORG", "TATAMOTORS", "TIINDIA", "TVSMOTOR"
]

NIFTY_FIN_SERVICE = [
    "BAJFINANCE", "BAJAJFINSV", "CHOLAFIN", "HDFC", "HDFCAMC",
    "HDFCBANK", "ICICIBANK", "ICICIGI", "ICICIPRULI", "LICHSGFIN",
    "M&MFIN", "RECLTD", "SBICARD", "SBILIFE", "SHRIRAMFIN"
]

NIFTY_METAL = [
    "COALINDIA", "HINDALCO", "JINDALSTEL", "JSWSTEEL", "MOIL",
    "NALCO", "NMDC", "RATNAMANI", "SAIL", "TATASTEEL",
    "VEDL", "WELCORP"
]

NIFTY_REALTY = [
    "BRIGADE", "DLF", "GODREJPROP", "LODHA", "OBEROIRLTY",
    "PHOENIXLTD", "PRESTIGE", "SOBHA", "SUNTECK"
]
